name: Test deployment

on:
  pull_request:
    branches:
      - main
    # Review gh actions docs if you want to further define triggers, paths, etc
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#on

jobs:
  test-deploy:
    name: Test deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm

      - name: Install dependencies
        run: pnpm install
      - name: Test build website
        run: pnpm build
        env:
          APPLICATION_ID: ${{ secrets.APPLICATION_ID }}
          SEARCH_KEY: ${{ secrets.SEARCH_KEY }}
          INDEX_NAME: ${{ secrets.INDEX_NAME }}
          INDEX_NAME_TMP: ${{ secrets.INDEX_NAME_TMP }}
          ALGOLIA_API_KEY: ${{ secrets.ALGOLIA_API_KEY }}