name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - run: git remote set-url origin https://git:${ACCESS_TOKEN}@github.com/gotitinc/aha.git
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      - run: yarn install
      - run: npm run build
        env:
          GATSBY_ALGOLIA_API_KEY: ${{ secrets.GATSBY_ALGOLIA_API_KEY }}
          GATSBY_ALGOLIA_APP_ID: ${{ secrets.GATSBY_ALGOLIA_APP_ID }}
          GATSBY_ALGOLIA_SEARCH_KEY: ${{ secrets.GATSBY_ALGOLIA_SEARCH_KEY }}
      - run: node apps/docs/deploy.js

